# Generated by Django 4.2.7 on 2023-11-21 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='age',
        ),
        migrations.AddField(
            model_name='cat',
            name='is_sleeping',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cat',
            name='happiness',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='cat',
            name='hunger',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='cat',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
